"""initial_schema

Revision ID: e88ab4a17d01
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 10:38:06.826043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e88ab4a17d01'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_migration_map_locations_new_id', table_name='migration_map_locations')
    op.drop_table('migration_map_locations')
    op.drop_index('ix_migration_map_amenities_new_id', table_name='migration_map_amenities')
    op.drop_table('migration_map_amenities')
    op.drop_index('ix_migration_map_properties_new_id', table_name='migration_map_properties')
    op.drop_table('migration_map_properties')
    op.drop_index('ix_migration_map_property_types_new_id', table_name='migration_map_property_types')
    op.drop_table('migration_map_property_types')
    op.drop_index('ix_proximities_property_id', table_name='proximities')
    op.drop_table('proximities')
    op.drop_index('ix_migration_map_users_new_id', table_name='migration_map_users')
    op.drop_table('migration_map_users')
    op.drop_index('ix_reviews_booking_id', table_name='reviews')
    op.drop_index('ix_reviews_property_id', table_name='reviews')
    op.drop_index('ix_reviews_service_id', table_name='reviews')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('overall_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('cleanliness_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('communication_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('checkin_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('accuracy_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('location_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('value_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comfort_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('security_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('accessibility_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('host_response_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='reviews_booking_id_fkey'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_reviews_property_id'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='reviews_service_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey'),
    sa.UniqueConstraint('service_id', 'user_id', name='uq_review_one_per_user')
    )
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_index('ix_reviews_service_id', 'reviews', ['service_id'], unique=False)
    op.create_index('ix_reviews_property_id', 'reviews', ['property_id'], unique=False)
    op.create_index('ix_reviews_booking_id', 'reviews', ['booking_id'], unique=False)
    op.create_table('migration_map_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migration_map_users_pkey'),
    sa.UniqueConstraint('old_id', name='uq_migration_map_users_old_id')
    )
    op.create_index('ix_migration_map_users_new_id', 'migration_map_users', ['new_id'], unique=False)
    op.create_table('proximities',
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('destination_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('minutes_away', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('travel_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='proximities_property_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='proximities_pkey')
    )
    op.create_index('ix_proximities_property_id', 'proximities', ['property_id'], unique=False)
    op.create_table('migration_map_property_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migration_map_property_types_pkey'),
    sa.UniqueConstraint('old_id', name='uq_migration_map_property_types_old_id')
    )
    op.create_index('ix_migration_map_property_types_new_id', 'migration_map_property_types', ['new_id'], unique=False)
    op.create_table('migration_map_properties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migration_map_properties_pkey'),
    sa.UniqueConstraint('old_id', name='uq_migration_map_properties_old_id')
    )
    op.create_index('ix_migration_map_properties_new_id', 'migration_map_properties', ['new_id'], unique=False)
    op.create_table('migration_map_amenities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migration_map_amenities_pkey'),
    sa.UniqueConstraint('old_id', name='uq_migration_map_amenities_old_id')
    )
    op.create_index('ix_migration_map_amenities_new_id', 'migration_map_amenities', ['new_id'], unique=False)
    op.create_table('migration_map_locations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migration_map_locations_pkey'),
    sa.UniqueConstraint('old_id', name='uq_migration_map_locations_old_id')
    )
    op.create_index('ix_migration_map_locations_new_id', 'migration_map_locations', ['new_id'], unique=False)
    # ### end Alembic commands ###

