import {
  AlarmSmoke,
  Bath,
  Briefcase,
  Building,
  Cctv,
  ChefHat,
  CircleParking,
  Droplet,
  Fan,
  Flame,
  HeartPulse,
  Microwave,
  Refrigerator,
  ShowerHead,
  Snowflake,
  Sprout,
  Sun,
  Tv,
  WashingMachine,
  Waves,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const AMENITY_ICONS: Record<string, LucideIcon> = {
  wifi: Wifi,
  kitchen: ChefHat,
  fridge: Refrigerator,
  microwave: Microwave,
  stove: Flame,
  ac: Snowflake,
  heating: Flame,
  fan: Fan,
  hot_water: Droplet,
  shower: ShowerHead,
  bathtub: Bath,
  washer: WashingMachine,
  dryer: WashingMachine,
  tv: Tv,
  workspace: Briefcase,
  free_parking: CircleParking,
  paid_parking: CircleParking,
  pool: Waves,
  garden: Sprout,
  balcony: Building,
  terrace: Sun,
  smoke_alarm: AlarmSmoke,
  first_aid_kit: HeartPulse,
  security_cameras: Cctv,
  backup_generator: Zap,
};
